# Generated by Django 4.1 on 2022-11-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reserva_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='observacion',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
